
services:
  postgres:
    image: postgres:16
    container_name: automation_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data_automation:/var/lib/postgresql/data
    
volumes:
  postgres_data_automation: